os:
- linux
matrix:
  include:
  - language: php
    php: '7.2'
    before_script:
    - composer self-update
    - composer install --no-interaction
    - cp .env.travis .env
    - pear install pear/PHP_CodeSniffer
    - phpenv rehash
    script:
    - vendor/bin/phpunit --coverage-text
  - language: node_js
    node_js: '8'
    before_script:
    - yarn
    script:
    - yarn run lint
    - yarn run production
deploy:
  provider: heroku
  api_key:
    secure: R2kAQYiU8rAynkEFPIKzJYz5k888hNMnmFdoDePJosJUf/G4jsEmkdPG7vsPPX33UI6dM1Py7gvv5ZoUbiTzFIbHNstnCJ2YVf97FlfOHgmXCf6wBc4B/V4VUAcFZ0RkDaQiGF34nVph8b3MuPGiNTITIIHg/+Im9eTEBXjoAuOtFUBH5Dkt/FHiseUXYbxp7H46H3rf2agFZUk/pOo0BuBPtXFahw3ysztxSbHYttsOoBFbR66aUEJRWPYDLm3wUn/pauxRCvBsIBSwKdHpRzZYEgiNzLAuuiDtNP4NCQVALUcVILRunanatZONnIAqKqvv6kkroZe0UnEZ5aNf9+5yXLlGPpaRAOA6btn3v71ndtk6aPOQ8toBt4lcJ1/wgtiila/5zbO/QbSn+pnSg5et4QO/cQCw8Wdo+aPIbpfDYN/13fQvbVTFQVhZhX4kSSDcYRkoMIcno17gNuyOhaU0QDBaX40KWJvEi45TJoJLLEs6ckdXTxd85cnxShckrLjbqGH2jLkphGuMX9+kbg5zMtCBMmmrzzEXnlj3a15xjgB41/pAQR9eplYyvzDnCJuC7Djy3ZIYkUgAiHJ12BHW9GjBE8ObVVZlK9wShgyAlAApt4OnNi+u2w1TaXhSUVWRMNnz79GXNP+jdfV2ywjIj1SpKSjIx645CaBZLs4=
  app: blog-marlin
  on:
    repo: bad4iz/blog-marlin
  run: "php artisan migrate"