os:
  - linux
matrix:
  include:
    - language: php
      php: "7.2"
      before_script:
        # - composer self-update
        # - composer install --no-interaction
        # - cp .env.travis .env
        # - pear install pear/PHP_CodeSniffer
        # - phpenv rehash
          - cp .env.travis .env
          - mysql -e 'create database homestead_test;'
          - composer self-update
          - composer install --no-interaction
      script:
        - vendor/bin/phpunit
        # - vendor/bin/phpunit --coverage-text
        # - phpcs --ignore=app/Http/Controllers/Controller.php app/Http/Controllers
    
    
    - language: node_js
      node_js: "8"  

      before_script:
        - yarn

      script:
        - yarn run lint
        - yarn run production