os:
  - linux
matrix:
  include:
    - language: php
      php: 
        - "7.1"
        - "7.2"
      before_script:
        - composer self-update
        - composer install --no-interaction
        - cp .env.travis .env
        - pear install pear/PHP_CodeSniffer
        - phpenv rehash

      script:
        - vendor/bin/phpunit --coverage-text
        # - phpcs --ignore=app/Http/Controllers/Auth,app/Http/Controllers/Controller.php app/Http/Controllers
    
    
    - language: node_js
      node_js: "8"  

      before_script:
        - yarn

      script:
        - yarn run lint
        - yarn run production