os:
- linux
matrix:
  include:
  - language: php
    php: '7.2'
    before_script:
    - composer self-update
    - composer install --no-interaction
    - cp .env.travis .env
    - pear install pear/PHP_CodeSniffer
    - phpenv rehash
    script:
    - vendor/bin/phpunit --coverage-text
  - language: node_js
    node_js: '8'
    before_script:
    - yarn
    script:
    - yarn run lint
    - yarn run production
deploy:
  provider: heroku
  api_key:
    secure: HzECkxjrBOsL34faktsk6cE02n9EQi+ehfy9gxoN5tOVsd1hopG81CbTa/7Ch3xQ9XY/D+Xe5RGYMsmfPl4sZs2ZPpnQQROSi7qraP/hzw2HLH84rh+d6c728EfqH/zThs94GWPh8J0UQVNOxxNWZapZSfY4JPvaqgkNwkoTZxuQI6kAk5YcLfGbOPL4nTDVaxp+iTzCFFi/Yhw67IahiKDd0ugb7nZk6EZAGyXggjHWmgLKz9riu/6MCv3e5GryiALKaQu2pVrQihy6GkNEJu7TA4yKw9NEaJUz1PZa8YIFh6ORYTiNNJEPikVoUric0zbMiy8Nd9QMYxsU8lhqLBV0wqlmja0wjBx5f1CVGRb4qdIIa6Ow4WMCpkq5DFajhcZEZC5WB94lCjOB3mH3mUgj+ceeZ9O5xTkAEGfjYEeZj2I70CoW3lsbeW8j9GJ6aFKBPOiRpqOH3yLPLkVsyEXUn6z2p+8EmFJpdedWF28UsZQ2g8evSVG7G3QZ7SDizUBtAFh/a5/6bLp4G7i+LMtwMD2twDaPsMyibJxxWdFukWT7a446xr+gmgsc92Pb4hHFT3E31pssZ8HOhkh56Jv6HKQK8dD/Hhq2O6raNGQdVSH6FCxD+hkaxXNDTESa8hgR6mvbeOtOXD3OmNaOq2GX6PeY5HiT12O7HaTKdT8=
  app: blog-marlin
  on:
    repo: bad4iz/blog-marlin
  run: php artisan migrate
